project:
  type: website
  preview: 
    port: 8080

website:
  title: "TJ"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: notes/index.qmd
        text: Notes
      - about.qmd

  page-footer:
    center: |
      {{< iconify ri:creative-commons-fill >}} 2025 Tiago Jacinto

format:
  html:
    theme: [default, skeletor.scss]
    css: styles.css
    toc: true
    include-in-header: includes/head.html

