project:
  type: website
  preview: 
    port: 8080

website:
  title: "Tiago Jacinto"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: notes/index.qmd
        text: Notes
      - about.qmd

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true



