project:
  type: website
  preview: 
    port: 8080

website:
  title: "Tiago Jacinto"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: notes/index.qmd
        text: Notes
      - about.qmd

  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-3WVN56HVND"
    anonymize-ip: true

  page-footer:
    left: |
      {{< iconify ri:creative-commons-fill >}} 2025 Tiago Jacinto
    center: |
      Made with [{{< iconify simple-icons:quarto>}}](https://quarto.org/)
    right: |
      [{{< iconify fa6-brands:github >}}](https://github.com/tgjac)
      [{{< iconify fa6-brands:linkedin-in >}}](https://www.linkedin.com/in/tgjac/)
      [{{< iconify fa6-brands:bluesky >}}](https://bsky.app/profile/tiagojacinto.eu)
      [{{< iconify fa6-brands:mastodon >}}](https://scicomm.xyz/@tiagojacinto)
      [{{< iconify fa6-brands:lastfm >}}](https://www.last.fm/user/tgjac)


format:
  html:
    theme: [default, skeletor.scss]
    css: styles.css
    toc: true
    include-in-header: includes/head.html

